const FormFields = {
    Up_police: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      address: true,
      skills: true,
      drivingLicense: true,
    },
    Delhi_police: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      address: true,
      city: true,
      zip: true,
      gender: true,
    },
    Mumbai_police: {
      firstName: true,
      lastName: true,
      phone: true,
      address: true,
      dob: true,
      gender: true,
      occupation: true,
    },
    Railway_Exam: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      qualification: true,
      university: true,
      passingYear: true,
    },
    SSC_Exam: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      qualification: true,
      percentage: true,
      skills: true,
    },
    Bank_PO: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      bankName: true,
      accountNumber: true,
      ifscCode: true,
    },
    Forest_Guard: {
      firstName: true,
      lastName: true,
      phone: true,
      dob: true,
      gender: true,
      bloodGroup: true,
      medicalHistory: true,
    },
    Teacher_Eligibility_Test: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      qualification: true,
      university: true,
      passingYear: true,
      experience: true,
    },
    Army_Recruitment: {
      firstName: true,
      lastName: true,
      phone: true,
      dob: true,
      gender: true,
      nationality: true,
      emergencyContact: true,
    },
    Navy_Exam: {
      firstName: true,
      lastName: true,
      email: true,
      phone: true,
      
      nationality: true,
      medicalHistory: true,
      passportNumber: true,
    },
  };
  
  const exams = [
    { title: 'UP_Police',  description: 'UP police commission ..', expire: 'Expire on 15/4/25', fields: FormFields.Up_police },
    { title: 'Delhi_Police', description: 'Delhi police recruitment ..', expire: 'Expire on 20/5/25', fields: FormFields.Delhi_police },
    { title: 'Mumbai_Police', description: 'Mumbai police drive ..', expire: 'Expire on 30/6/25', fields: FormFields.Mumbai_police },
    { title: 'Railway_Exam', description: 'Indian railway job exam ..', expire: 'Expire on 25/7/25', fields: FormFields.Railway_Exam },
    { title: 'SSC_Exam', description: 'SSC combined graduate level ..', expire: 'Expire on 10/8/25', fields: FormFields.SSC_Exam },
    { title: 'Bank_PO', description: 'Bank probationary officer exam ..', expire: 'Expire on 5/9/25', fields: FormFields.Bank_PO },
    { title: 'Forest_Guard', description: 'Forest guard recruitment ..', expire: 'Expire on 18/10/25', fields: FormFields.Forest_Guard },
    { title: 'Teacher_Eligibility Test', description: 'State teacher eligibility test ..', expire: 'Expire on 2/11/25', fields: FormFields.Teacher_Eligibility_Test },
    { title: 'Army_Recruitment', description: 'Indian army recruitment rally ..', expire: 'Expire on 15/12/25', fields: FormFields.Army_Recruitment },
    { title: 'Navy_Exam', description: 'Indian navy entrance test ..', expire: 'Expire on 8/1/26', fields: FormFields.Navy_Exam },
  ];
  
  export { FormFields, exams };
  